// Generated by Wrangler from wrangler.jsonc
// DO NOT EDIT — run `pnpm types` to regenerate

declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "JobResearchAgent";
	}
	interface Env {
		AI: Ai;
		ASSETS: Fetcher;
		JobResearchAgent: DurableObjectNamespace /* JobResearchAgent */;
	}
}
interface Env extends Cloudflare.Env {}
